# Generated by Django 5.1.15 on 2026-04-12 23:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_id', models.CharField(help_text='Unique exercise identifier, e.g. "a_n", "i_h", "phrase"', max_length=50, unique=True)),
                ('title', models.CharField(help_text='Display title, e.g. "Vokal A"', max_length=100)),
                ('description', models.TextField(help_text='Instructions for the patient')),
                ('example_audio_url', models.CharField(blank=True, default='', help_text='Path to example audio file', max_length=500)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this exercise is currently in use')),
            ],
            options={
                'verbose_name': 'Übung',
                'verbose_name_plural': 'Übungen',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.CharField(help_text='Pseudonym des Patienten (kein echter Name)', max_length=100, unique=True, verbose_name='Pseudonym')),
                ('status', models.CharField(choices=[('NEW', 'Neu'), ('CONSENT_GIVEN', 'Einwilligung erteilt'), ('PRE_OP_DONE', 'Prä-OP abgeschlossen'), ('POST_OP_STARTED', 'Post-OP begonnen'), ('POST_OP_DONE', 'Post-OP abgeschlossen'), ('COMPLETED', 'Abgeschlossen'), ('EXPIRED', 'Abgelaufen')], default='NEW', max_length=20, verbose_name='Status')),
                ('pre_op_date', models.DateTimeField(blank=True, null=True, verbose_name='Prä-OP Datum')),
                ('post_op_date', models.DateTimeField(blank=True, null=True, verbose_name='Post-OP Datum')),
                ('prediction_pre', models.CharField(choices=[('TODO', 'Ausstehend'), ('INFECTED', 'Pathologisch'), ('HEALTHY', 'Gesund')], default='TODO', max_length=10, verbose_name='KI-Vorhersage (Prä-OP)')),
                ('ai_percentage_rp_pre', models.FloatField(blank=True, null=True, verbose_name='KI Wahrscheinlichkeit Prä-OP (%)')),
                ('gradcam_prediction_pre', models.CharField(blank=True, default='', max_length=20, verbose_name='GradCAM Vorhersage (Prä-OP)')),
                ('gradcam_percentage_pre', models.FloatField(blank=True, null=True, verbose_name='GradCAM Wahrscheinlichkeit Prä-OP (%)')),
                ('ai_reasoning_pre', models.TextField(blank=True, default='', verbose_name='KI-Begründung (Prä-OP)')),
                ('prediction_post', models.CharField(choices=[('TODO', 'Ausstehend'), ('INFECTED', 'Pathologisch'), ('HEALTHY', 'Gesund')], default='TODO', max_length=10, verbose_name='KI-Vorhersage (Post-OP)')),
                ('ai_percentage_rp_post', models.FloatField(blank=True, null=True, verbose_name='KI Wahrscheinlichkeit Post-OP (%)')),
                ('gradcam_prediction_post', models.CharField(blank=True, default='', max_length=20, verbose_name='GradCAM Vorhersage (Post-OP)')),
                ('gradcam_percentage_post', models.FloatField(blank=True, null=True, verbose_name='GradCAM Wahrscheinlichkeit Post-OP (%)')),
                ('ai_reasoning_post', models.TextField(blank=True, default='', verbose_name='KI-Begründung (Post-OP)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('expires_at', models.DateTimeField(help_text='Datum, ab dem der Datensatz gelöscht werden soll', verbose_name='Läuft ab am')),
                ('notification_sent_at', models.DateTimeField(blank=True, help_text='Zeitpunkt, zu dem die Ablauf-Benachrichtigung versendet wurde', null=True, verbose_name='Benachrichtigung gesendet am')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Zeitpunkt der Soft-Löschung (Audiodaten entfernt, Metadaten bleiben)', null=True, verbose_name='Gelöscht am')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patienten',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecordingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase', models.CharField(choices=[('PRE_OP', 'Prä-OP'), ('POST_OP', 'Post-OP')], max_length=10, verbose_name='Phase')),
                ('session_number', models.PositiveIntegerField(help_text='Sequential number per patient and phase (1, 2, 3, …)', verbose_name='Sitzungsnummer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='patients.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Aufnahmesitzung',
                'verbose_name_plural': 'Aufnahmesitzungen',
                'ordering': ['created_at'],
                'unique_together': {('patient', 'phase', 'session_number')},
            },
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exercise_id', models.CharField(help_text='References Exercise.exercise_id', max_length=50, verbose_name='Übungs-ID')),
                ('phase', models.CharField(choices=[('PRE_OP', 'Prä-OP'), ('POST_OP', 'Post-OP')], default='PRE_OP', max_length=10, verbose_name='Phase')),
                ('storage_key', models.CharField(help_text='S3/MinIO object key', max_length=500, verbose_name='Speicher-Schlüssel')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='patients.patient', verbose_name='Patient')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='patients.recordingsession', verbose_name='Aufnahmesitzung')),
            ],
            options={
                'verbose_name': 'Audiodatei',
                'verbose_name_plural': 'Audiodateien',
                'ordering': ['created_at'],
            },
        ),
    ]
