# Generated by Django 5.1.15 on 2026-04-02 19:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_id', models.CharField(help_text='Unique exercise identifier, e.g. "a_n", "i_n", "phrase"', max_length=50, unique=True)),
                ('title', models.CharField(help_text='Display title, e.g. "Vokal A"', max_length=100)),
                ('description', models.TextField(help_text='Instructions for the patient')),
                ('example_audio_url_female', models.CharField(blank=True, default='', help_text='Path to female example audio', max_length=500)),
                ('example_audio_url_male', models.CharField(blank=True, default='', help_text='Path to male example audio', max_length=500)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this exercise is currently in use')),
            ],
            options={
                'verbose_name': 'Übung',
                'verbose_name_plural': 'Übungen',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.CharField(help_text='Lesbare Patienten-ID (z.B. vom Krankenhaus vergeben)', max_length=100, unique=True, verbose_name='Patienten-ID')),
                ('status', models.CharField(choices=[('NEW', 'Neu'), ('CONSENT_GIVEN', 'Einwilligung erteilt'), ('DEMOGRAPHICS_DONE', 'Demografie abgeschlossen'), ('PRE_OP_DONE', 'Prä-OP abgeschlossen'), ('POST_OP_STARTED', 'Post-OP begonnen'), ('POST_OP_DONE', 'Post-OP abgeschlossen'), ('COMPLETED', 'Abgeschlossen')], default='NEW', max_length=20, verbose_name='Status')),
                ('gender', models.CharField(choices=[('M', 'Männlich'), ('W', 'Weiblich'), ('D', 'Divers'), ('?', 'Unbekannt')], default='?', max_length=1, verbose_name='Geschlecht')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Geburtsdatum')),
                ('pre_op_date', models.DateTimeField(blank=True, null=True, verbose_name='Prä-OP Datum')),
                ('post_op_date', models.DateTimeField(blank=True, null=True, verbose_name='Post-OP Datum')),
                ('diagnosis', models.CharField(choices=[('LEFT', 'Links'), ('RIGHT', 'Rechts'), ('BOTH', 'Beidseitig'), ('HEALTHY', 'Gesund'), ('TODO', 'Ausstehend')], default='TODO', max_length=10, verbose_name='Diagnose')),
                ('diagnosis_text', models.TextField(blank=True, default='', help_text='Optionale zusätzliche Diagnose-Details', verbose_name='Diagnose (Freitext)')),
                ('prediction_pre', models.CharField(choices=[('TODO', 'Ausstehend'), ('INFECTED', 'Pathologisch'), ('HEALTHY', 'Gesund')], default='TODO', max_length=10, verbose_name='KI-Vorhersage (Prä-OP)')),
                ('ai_percentage_rp_pre', models.FloatField(blank=True, null=True, verbose_name='KI Wahrscheinlichkeit Prä-OP (%)')),
                ('gradcam_prediction_pre', models.CharField(blank=True, default='', max_length=20, verbose_name='GradCAM Vorhersage (Prä-OP)')),
                ('gradcam_percentage_pre', models.FloatField(blank=True, null=True, verbose_name='GradCAM Wahrscheinlichkeit Prä-OP (%)')),
                ('ai_reasoning_pre', models.TextField(blank=True, default='', verbose_name='KI-Begründung (Prä-OP)')),
                ('prediction_post', models.CharField(choices=[('TODO', 'Ausstehend'), ('INFECTED', 'Pathologisch'), ('HEALTHY', 'Gesund')], default='TODO', max_length=10, verbose_name='KI-Vorhersage (Post-OP)')),
                ('ai_percentage_rp_post', models.FloatField(blank=True, null=True, verbose_name='KI Wahrscheinlichkeit Post-OP (%)')),
                ('gradcam_prediction_post', models.CharField(blank=True, default='', max_length=20, verbose_name='GradCAM Vorhersage (Post-OP)')),
                ('gradcam_percentage_post', models.FloatField(blank=True, null=True, verbose_name='GradCAM Wahrscheinlichkeit Post-OP (%)')),
                ('ai_reasoning_post', models.TextField(blank=True, default='', verbose_name='KI-Begründung (Post-OP)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patienten',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exercise_id', models.CharField(help_text='References Exercise.exercise_id', max_length=50, verbose_name='Übungs-ID')),
                ('phase', models.CharField(choices=[('PRE_OP', 'Prä-OP'), ('POST_OP', 'Post-OP')], default='PRE_OP', max_length=10, verbose_name='Phase')),
                ('storage_key', models.CharField(help_text='S3/MinIO object key', max_length=500, verbose_name='Speicher-Schlüssel')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='patients.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Audiodatei',
                'verbose_name_plural': 'Audiodateien',
                'ordering': ['created_at'],
            },
        ),
    ]
