# Generated by Django 5.1.15 on 2026-05-04

import uuid
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_add_last_exported_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase', models.CharField(choices=[('PRE_OP', 'Prä-OP'), ('POST_OP', 'Post-OP')], max_length=10, verbose_name='Phase')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Bewertung (1-5)')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Kommentar')),
                ('skipped', models.BooleanField(default=False, verbose_name='Übersprungen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='patients.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
                'ordering': ['-created_at'],
                'unique_together': {('patient', 'phase')},
            },
        ),
        migrations.CreateModel(
            name='ExerciseSkip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase', models.CharField(choices=[('PRE_OP', 'Prä-OP'), ('POST_OP', 'Post-OP')], max_length=10, verbose_name='Phase')),
                ('exercise_id', models.CharField(help_text='References Exercise.exercise_id', max_length=50, verbose_name='Übungs-ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_skips', to='patients.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Übung übersprungen',
                'verbose_name_plural': 'Übungen übersprungen',
                'ordering': ['-created_at'],
                'unique_together': {('patient', 'phase', 'exercise_id')},
            },
        ),
    ]
