# Generated by Django 5.1.15 on 2026-05-14 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_remove_completed_expired_statuses'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exerciseskip',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='exerciseskip',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercise_skips', to='patients.recordingsession', verbose_name='Sitzung'),
        ),
        migrations.AlterField(
            model_name='exerciseskip',
            name='phase',
            field=models.CharField(choices=[('PRE_OP', 'Prä-OP'), ('POST_OP', 'Post-OP')], help_text='Kept for backward compat and admin display; uniqueness enforced via session.', max_length=10, verbose_name='Phase'),
        ),
        migrations.AlterUniqueTogether(
            name='exerciseskip',
            unique_together={('patient', 'session', 'exercise_id')},
        ),
    ]
