# Generated by Django 5.1.15 on 2026-06-10 16:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_loginhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('create', 'Erstellt'), ('upload', 'Upload'), ('delete', 'Löschung'), ('export', 'Export'), ('edit', 'Bearbeitet'), ('expiry', 'Ablauf'), ('view', 'Zugriff')], max_length=20, verbose_name='Ereignistyp')),
                ('event', models.CharField(help_text='Short German label shown in the UI timeline', max_length=200, verbose_name='Ereignis')),
                ('detail', models.CharField(blank=True, default='', max_length=500, verbose_name='Details')),
                ('files', models.JSONField(blank=True, default=list, help_text='List of file name strings, e.g. ["Aufnahme 1 [A_N]", "Aufnahme 2 [I_H]"]', verbose_name='Betroffene Dateien')),
                ('actor', models.CharField(choices=[('admin', 'Admin'), ('patient', 'Patient'), ('system', 'System')], max_length=10, verbose_name='Akteur')),
                ('actor_name', models.CharField(help_text='Username, patient pseudonym, or "System"', max_length=200, verbose_name='Akteur-Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Zeitpunkt')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='patients.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Audit-Eintrag',
                'verbose_name_plural': 'Audit-Einträge',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', '-created_at'], name='patients_pa_patient_fdb980_idx')],
            },
        ),
    ]
