# Generated by Django 5.1.15 on 2026-06-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_add_patient_audit_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordingsession',
            name='visit_date',
            field=models.DateTimeField(blank=True, help_text='Datum dieses Aufnahmetermins (für Follow-up-Sitzungen; Sitzung 1 verwendet weiterhin Patient.pre_op_date/post_op_date).', null=True, verbose_name='Besuchsdatum'),
        ),
    ]
