# Generated by Django 5.1.15 on 2026-07-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_recordingsession_visit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='access_code',
            field=models.CharField(editable=False, help_text='Alternativer Zugangscode, falls der QR-Code-Scan fehlschlägt', max_length=8, null=True, unique=True, verbose_name='Zugangscode'),
        ),
    ]
